const starObject = {
  data:[
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
    {data: {
      left: Math.floor(Math.random() * 100) + 'px',
      top: Math.floor(Math.random() * 100) + 'px',
      'background-color': 'white',
      height: '8px',
      position: 'absolute',
      width: '8px',
    }},
  ]
}

export default starObject;